# Generated by Django 3.0.7 on 2020-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('target', models.CharField(max_length=100, verbose_name='Предназначение')),
                ('name', models.SlugField(max_length=300, unique=True, verbose_name='Имя бота')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('chat_id', models.SmallIntegerField(verbose_name='Чат id')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
