# Generated by Django 3.0.7 on 2020-07-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200704_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chat_id',
            field=models.IntegerField(verbose_name='Чат id'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Имя бота'),
        ),
    ]
