# Generated by Django 3.0.7 on 2020-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200704_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Чат id'),
        ),
    ]
