# Generated by Django 3.0.7 on 2020-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200704_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
    ]
