# Generated by Django 3.0.7 on 2020-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
        migrations.AlterField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
    ]
