# Generated by Django 3.0.7 on 2020-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200614_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='от 1 до 7', null=True, verbose_name='Рэйтинг'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
