# Generated by Django 3.0.7 on 2020-06-25 16:44

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0017_auto_20200620_0557'),
        ('forum', '0006_auto_20200625_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('icon', models.TextField(help_text='Вставить из fontawesome.com', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Наименование показателя')),
                ('number', models.CharField(blank=True, help_text='Например, 80%', max_length=30, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, max_length=1000, verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(blank=True, help_text='Необходим для сортировки вопросов', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Имя')),
                ('text', models.TextField(blank=True, max_length=2000, verbose_name='Тексты отзыва или мнения')),
                ('position', models.CharField(blank=True, help_text='Например: должность', max_length=500, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Отзыв или мнение',
                'verbose_name_plural': 'Отзывы и мнения',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('short_title', models.CharField(blank=True, help_text='Заголовок, который будет под иконкой', max_length=100, verbose_name='Короткий заголовок')),
                ('icon', models.CharField(help_text='Вставить из fontawesome.com', max_length=200, verbose_name='Иконка')),
                ('short_description', models.TextField(help_text='Будет на странице проекта', max_length=1000, verbose_name='Короткое описание')),
                ('image', models.ImageField(blank=True, upload_to='files/project/', verbose_name='Картинка')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание')),
                ('slug', models.SlugField(help_text='Ссылка. Писать на латинице и без пробелов _', max_length=100, unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(blank=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Структура проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название проекта')),
                ('short_description', models.TextField(help_text='Будет отображаться в списке проектов', max_length=700, verbose_name='Краткое описание проекта')),
                ('image', models.ImageField(blank=True, help_text='Будет отображаться в списке проектов', upload_to='files/project/', verbose_name='Картинка проекта')),
                ('title', models.CharField(blank=True, help_text='Заголовок черного цвета', max_length=200, verbose_name='Заголовок проекта')),
                ('title_grey', models.CharField(blank=True, help_text='Заголовок серого цвета', max_length=200, verbose_name='Заголовок проекта серый')),
                ('body', models.TextField(help_text='Будет отображаться в списке проектов', max_length=700, verbose_name='Карткое описание проекта')),
                ('description_first_title', models.CharField(blank=True, max_length=30, verbose_name='Описание 1 - Заголовок')),
                ('description_first', models.CharField(blank=True, max_length=1000, verbose_name='Описание 1')),
                ('description_second_title', models.CharField(blank=True, max_length=30, verbose_name='Описание 2 - Заголовок')),
                ('description_second', models.CharField(blank=True, max_length=1000, verbose_name='Описание 2')),
                ('video_title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок для блока видео')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('order', models.PositiveSmallIntegerField(help_text='Необходим для сортировки проектов', verbose_name='Порядковый номер проекта')),
                ('slug', models.SlugField(help_text='Должен быть уникальным, только на латинице, вместо пробелов использовать _', max_length=100, unique=True, verbose_name='Slug проекта')),
                ('draft', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('show_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('benefits', models.ManyToManyField(blank=True, to='project.Benefits', verbose_name='Преимущество')),
                ('company', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company', verbose_name='Компания')),
                ('data', models.ManyToManyField(blank=True, related_name='title', to='project.Data', verbose_name='Показатели')),
                ('forum_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Theme', verbose_name='Тема на форуме')),
                ('questions', models.ManyToManyField(blank=True, to='project.Questions', verbose_name='Вопросы и ответы')),
                ('reviews', models.ManyToManyField(blank=True, to='project.Review', verbose_name='Отзывы или мнения')),
                ('structure_element', models.ManyToManyField(blank=True, to='project.Structure', verbose_name='Структура проекта')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
    ]
