# Generated by Django 3.0.7 on 2020-06-25 21:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='deta_int',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Значение шкалы от 1 до 100', null=True, verbose_name='Значение шкалы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='project.Benefits', verbose_name='Преимуществa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_first',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_second',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет на странице проекта', max_length=2000, verbose_name='Короткое описание'),
        ),
    ]
