# Generated by Django 3.0.7 on 2020-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200626_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
