# Generated by Django 3.0.7 on 2020-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200702_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='icon',
            field=models.TextField(help_text='Выбрать на сайте https://www.icofont.com/icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='icon',
            field=models.TextField(help_text='Выбрать на сайте https://www.icofont.com/icons', verbose_name='Иконка'),
        ),
    ]
