# Generated by Django 3.0.7 on 2020-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200702_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
    ]
