# Generated by Django 3.0.7 on 2020-07-03 09:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200702_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='data',
            name='deta_int',
            field=models.PositiveSmallIntegerField(default=0, help_text='Значение шкалы от 1 до 100', verbose_name='Значение шкалы'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование показателя'),
        ),
        migrations.AlterField(
            model_name='data',
            name='number',
            field=models.CharField(help_text='Например, 80%', max_length=30, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='data',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_first',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_first_title',
            field=models.CharField(max_length=30, verbose_name='Описание 1 - Заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_second',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_second_title',
            field=models.CharField(max_length=30, verbose_name='Описание 2 - Заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Будет отображаться в списке проектов', upload_to='files/project/', verbose_name='Картинка проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='structure_element',
            field=models.ManyToManyField(to='project.Structure', verbose_name='Структура проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Заголовок черного цвета', max_length=200, verbose_name='Заголовок проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_grey',
            field=models.CharField(help_text='Заголовок серого цвета', max_length=200, verbose_name='Заголовок проекта серый'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_title',
            field=models.CharField(max_length=300, verbose_name='Заголовок для блока видео'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Необходим для сортировки вопросов', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(help_text='Например: должность', max_length=500, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Тексты отзыва или мнения'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(upload_to='files/project/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='short_title',
            field=models.CharField(help_text='Заголовок, который будет под иконкой', max_length=100, verbose_name='Короткий заголовок'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
