# Generated by Django 3.0.7 on 2020-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_structure_short_description_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='short_description_seo',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание для CEO (необязательно)'),
        ),
    ]
