# Generated by Django 3.0.7 on 2020-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200707_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentations',
            field=models.FileField(blank=True, upload_to=None, verbose_name='Презентация проекта в формате pdf'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Будет отображаться в списке проектов', upload_to=None, verbose_name='Картинка проекта'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(upload_to=None, verbose_name='Картинка'),
        ),
    ]
