# Generated by Django 3.0.7 on 2020-07-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200729_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='presentations',
            new_name='presentation',
        ),
    ]
