# Generated by Django 3.0.7 on 2020-06-15 14:33

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок темы')),
                ('preview', models.TextField(max_length=700, verbose_name='Отрывок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Тело темы (Начало не должно иметь быть заголовком или картинкой - только обычное форматирование)')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='URL темы')),
                ('draft', models.BooleanField(default=False, verbose_name='Опубликовать?')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('like', models.PositiveSmallIntegerField(default=0, verbose_name='Количество лайков')),
                ('dislike', models.PositiveSmallIntegerField(default=0, verbose_name='Количество дислайков')),
                ('show_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=3000, verbose_name='Ответ')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('draft', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Comment', verbose_name='Родитель')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
