# Generated by Django 3.0.7 on 2020-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200625_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='key',
        ),
        migrations.DeleteModel(
            name='UserIp',
        ),
    ]
