# Generated by Django 3.0.7 on 2020-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200702_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок темы'),
        ),
    ]
