# Generated by Django 3.0.7 on 2020-07-04 16:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0008_auto_20200703_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('text', models.TextField(max_length=2000, verbose_name='Тексты отзыва или мнения')),
                ('position', models.CharField(help_text='Например: должность', max_length=500, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Отзыв или мнение',
                'verbose_name_plural': 'Отзывы и мнения',
            },
        ),
        migrations.CreateModel(
            name='CompanySocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название соцсети')),
                ('icon', models.CharField(max_length=300, verbose_name='Иконка')),
                ('url', models.URLField(verbose_name='Ссылка на профиль в сети')),
            ],
            options={
                'verbose_name': 'Профиль в соцсети',
                'verbose_name_plural': 'Профили в соцсети',
            },
        ),
        migrations.CreateModel(
            name='PartnerForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет выводится на главной странице', max_length=200, verbose_name='Короткоe описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Форма партнерства',
                'verbose_name_plural': 'Формы партнерства',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('logo', models.ImageField(help_text='В альбомной ориентации', upload_to='files/partners/image/', verbose_name='Логотип партнера')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='QuestionsAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=1000, verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(help_text='Необходим для сортировки вопросов', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок - название компании')),
                ('slogan', models.TextField(verbose_name='Слоган - будет на первом экране сайта')),
                ('about_short', ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет выводится на главной странице', verbose_name='Коротко о краудфандинге')),
                ('logo', models.ImageField(upload_to='files/about/image/', verbose_name='Логотип компании')),
                ('image', models.ImageField(help_text='В хорошем качестве', upload_to='files/about/image/', verbose_name='Картинка компании')),
                ('number', models.PositiveSmallIntegerField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет выводится на главной странице', verbose_name='Развернуто о краудфандинге')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('forum_company_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Theme', verbose_name='Тема на форуме')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
