# Generated by Django 3.0.7 on 2020-07-05 11:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название области или региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Координата Х')),
                ('y', models.FloatField(verbose_name='Координата y')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет отображаться на карте', verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
