# Generated by Django 3.0.7 on 2020-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200705_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты на карте'},
        ),
        migrations.AddField(
            model_name='map',
            name='map_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок для объекта на карте (необязательно)'),
        ),
    ]
