# Generated by Django 3.0.7 on 2020-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200706_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='x',
        ),
        migrations.RemoveField(
            model_name='map',
            name='y',
        ),
        migrations.AddField(
            model_name='map',
            name='x_y',
            field=models.CharField(max_length=100, null=True, verbose_name='Координаты'),
        ),
    ]
