# Generated by Django 3.0.7 on 2020-07-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200706_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='x_y',
        ),
        migrations.AddField(
            model_name='map',
            name='x',
            field=models.FloatField(null=True, verbose_name='Координата Х'),
        ),
        migrations.AddField(
            model_name='map',
            name='y',
            field=models.FloatField(null=True, verbose_name='Координата y'),
        ),
    ]
