# Generated by Django 3.0.7 on 2020-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200707_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='slug',
            field=models.SlugField(help_text='ВНИМАНИЕ! Если это общие правила, то указать "general", для инвесторов "investor"', unique=True, verbose_name='Slug'),
        ),
    ]
