# Generated by Django 3.0.7 on 2020-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200708_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='consultant_code',
            field=models.TextField(blank=True, verbose_name='Код консультанта'),
        ),
    ]
