# Generated by Django 3.0.7 on 2020-07-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_company_consultant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='right_widget',
            field=models.TextField(blank=True, verbose_name='Виджет в Header'),
        ),
    ]
