# Generated by Django 3.0.7 on 2020-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_company_right_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер телефона'),
        ),
    ]
