# Generated by Django 3.0.7 on 2020-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200610_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
