# Generated by Django 3.0.7 on 2020-06-10 13:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200610_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о пользователе'),
        ),
    ]
