# Generated by Django 3.0.7 on 2020-06-10 15:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200610_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.SlugField(default=django.contrib.auth.models.User, unique=True, verbose_name='URL'),
        ),
    ]
