# Generated by Django 3.0.7 on 2020-06-10 18:52

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20200611_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professional',
            field=models.CharField(blank=True, max_length=200, verbose_name='Профессия'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='ФИО или название компании')),
                ('logo', models.ImageField(blank=True, upload_to='files/company/logo/', verbose_name='Логотип')),
                ('slogan', models.TextField(blank=True, max_length=500, verbose_name='Слоган')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о пользователе')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
                ('vk', models.SlugField(blank=True, max_length=200, verbose_name='Ссылка на профиль ВКонтакте')),
                ('fb', models.SlugField(blank=True, max_length=200, verbose_name='Ссылка на профиль Facebook')),
                ('instagram', models.SlugField(blank=True, max_length=200, verbose_name='Ссылка на профиль Instagram')),
                ('url', models.SlugField(default=django.contrib.auth.models.User, unique=True, verbose_name='URL')),
                ('cooperator', models.ManyToManyField(blank=True, related_name='Сотрудники', to=settings.AUTH_USER_MODEL, verbose_name='cooperator')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-register_date'],
            },
        ),
    ]
