# Generated by Django 3.0.7 on 2020-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200611_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_legal',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Название компании'),
        ),
    ]
