# Generated by Django 3.0.7 on 2020-06-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_company_name_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cooperator',
            field=models.ManyToManyField(blank=True, to='user.Profile', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_legal',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Юридическое название компании'),
        ),
    ]
