# Generated by Django 3.0.7 on 2020-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200611_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Основной номер телефона'),
        ),
        migrations.AddField(
            model_name='company',
            name='second_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дополнительный номер телефона (необязательно)'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер Whatapp (необязательно)'),
        ),
    ]
