# Generated by Django 3.0.7 on 2020-06-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200611_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Необходимо вместо +7 или 8 указать просто 7. Указывать номер обязательно без пробелов тире и других знаков ', max_length=30, verbose_name='Номер Whatapp (необязательно)'),
        ),
    ]
