# Generated by Django 3.0.7 on 2020-06-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200611_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_phone',
            field=models.CharField(blank=True, help_text='Указывать необязательно. Будет публиковано на сайте', max_length=30, verbose_name='Основной номер телефона'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_phone',
            field=models.CharField(blank=True, help_text='Указывать необязательно. Будет публиковано на сайте', max_length=30, verbose_name='Дополнительный номер телефона (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Необходимо вместо +7 или 8 указать просто 7. Указывать номер обязательно без пробелов тире и других знаков ', max_length=30, verbose_name='Номер Whatapp (необязательно)'),
        ),
    ]
