# Generated by Django 3.0.7 on 2020-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200611_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='250x250px', upload_to='files/users/avatars/', verbose_name='Аватар'),
        ),
    ]
