# Generated by Django 3.0.7 on 2020-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200702_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fb',
            field=models.URLField(blank=True, verbose_name='Ссылка на профиль Facebook'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Ссылка на профиль Instagram'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vk',
            field=models.URLField(blank=True, verbose_name='Ссылка на профиль ВКонтакте'),
        ),
    ]
