# Generated by Django 3.0.7 on 2020-07-03 09:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200702_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='files/company/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slogan',
            field=models.TextField(max_length=500, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='company',
            name='specialization',
            field=models.CharField(max_length=200, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(help_text='250x250px', upload_to='files/users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=500, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional',
            field=models.CharField(max_length=200, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.TextField(max_length=500, verbose_name='Слоган'),
        ),
    ]
